export type Course = {
  slug: string;
  title: string;
  subtitle: string;
  level: "Iniciante" | "Intermediário" | "Avançado" | "Do Básico ao Avançado" | "Workflow Completo" | "Graduação ao Doutorado";
  duration: string;
  priceText: string;
  hotmartCheckoutUrl: string;
  tags: string[];

  // NOVO
  image: string; // caminho em /public - imagem para o card
  imagePage?: string; // caminho em /public - imagem para a página de detalhes (opcional, usa `image` se não fornecido)
  imageVideo?: string; // caminho em /public - imagem para o vídeo/thumbnail (opcional, usa `imagePage` ou `image` se não fornecido)
  bullets: string[]; // mini lista "o que você vai aprender"
  outcome: string; // resultado final / promessa
  instructor: string; // Nome do instrutor/autor
  
  // Campos para Software/Ferramenta
  toolName?: string; // Nome técnico da ferramenta (ex: "TerraMetrics Pro")
  application?: string; // Aplicação/Problema resolvido (ex: "Análise de Transição de Uso da Terra")
  
  // Para promoções (estilo geomatica.pe)
  originalPrice?: number; // Preço original (sem desconto)
  discountPrice?: number; // Preço com desconto
  discountPercent?: number; // Percentual de desconto
  isPromo?: boolean; // Se está em promoção
};

export const COURSES: Course[] = [
  {
    slug: "transicao-uso-cobertura",
    title: "Dinâmica e Transição de Uso e Cobertura da Terra",
    subtitle: "Automatize a análise temporal a partir de dados governamentais e gere inteligência territorial completa em poucos minutos.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "R$ 297,00",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["R", "Uso do Solo", "Análise Temporal", "Automação"],
    image: "/courses/capa-curso-terrametrics.webp.webp",
    imagePage: "/courses/capa-curso-terrametrics.webp.webp",
    imageVideo: "/courses/capa-curso-terrametrics.webp.webp",
    toolName: "TerraMetrics Pro",
    application: "Análise Avançada de Transição de Uso e Cobertura da Terra",
    bullets: [
      "Acesso Vitalício à Ferramenta TerraMetrics Pro",
      "Cruzamento automático de mapas multitemporais",
      "Geração de mapas, matrizes e métricas de transição sem erros",
      "Gráficos profissionais de mudança de uso e cobertura da terra",
    ],
    outcome: "Você sai com um script pronto em R e metodologia completa para análises de transição de uso da terra, gerando resultados profissionais em minutos.",
    instructor: "Wellmo Alves",
    originalPrice: 397,
    discountPrice: 297,
    discountPercent: 25,
    isPromo: true,
  },
  {
    slug: "potencial-uso-conservacionista",
    title: "Planejamento de Uso Conservacionista do Solo",
    subtitle: "Gere mapas de capacidade de uso da terra em minutos e aplique critérios técnicos automatizados para adequação ambiental e agrícola.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Conservação", "Uso do Solo", "Planejamento", "Automação"],
    image: "/courses/potencial-uso-conservacionista.png",
    bullets: [
      "Acesso à Ferramenta Soil Capacity Classifier",
      "Classificação automática da capacidade de uso do solo",
      "Aplicação objetiva de critérios conservacionistas",
      "Mapas técnicos prontos para planejamento ambiental",
    ],
    outcome: "Você domina a metodologia completa para mapear e analisar o potencial de uso conservacionista, gerando mapas e análises técnicas profissionais para seus projetos.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "modelagem-perda-solos-rusle",
    title: "Modelagem de Erosão de Solos com RUSLE/USLE",
    subtitle: "Estime a perda de solo (t/ha/ano) e compreenda os fatores da RUSLE/USLE aplicados ao planejamento conservacionista, com execução automatizada e padrão técnico.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["USLE", "Erosão", "Modelagem", "Conservação"],
    image: "/courses/modelagem-perda-solos-rusle.png",
    bullets: [
      "Acesso à Ferramenta RUSLE Auto-Modeler",
      "Cálculo automatizado dos fatores da RUSLE/USLE",
      "Integração de fatores da RUSLE/USLE",
      "Mapas técnicos de perda de solo prontos para uso",
    ],
    outcome: "Você domina a metodologia completa da RUSLE e consegue gerar mapas profissionais de perda de solos para projetos ambientais, agrícolas e de conservação.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "estudo-fragilidade-ambiental",
    title: "Estudo da Fragilidade Ambiental",
    subtitle: "Mapeie a vulnerabilidade natural dos ambientes e gere zonas de fragilidade ambiental a partir do cruzamento automatizado de solo, relevo e clima.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Fragilidade", "Zoneamento", "Planejamento", "Automação"],
    image: "/courses/estudo-fragilidade-ambiental.png",
    bullets: [
      "Acesso à Ferramenta Environmental Fragility Modeler",
      "Cruzamento automatizado de variáveis ambientais",
      "Geração de classes de fragilidade ambiental",
      "Mapas técnicos prontos para zoneamento e licenciamento",
    ],
    outcome: "Você domina a metodologia completa para mapear e analisar a fragilidade ambiental, gerando mapas e análises técnicas profissionais para seus projetos.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "analise-vulnerabilidade-riscos-ambientais",
    title: "Análise de Vulnerabilidade e Riscos Ambientais",
    subtitle: "Avalie riscos em ambientes naturais e antropizados por meio da integração automatizada de variáveis ambientais e antrópicas para suporte à decisão.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Vulnerabilidade", "Risco", "Planejamento", "Automação"],
    image: "/courses/analise-vulnerabilidade-riscos-ambientais.png",
    bullets: [
      "Acesso à Ferramenta Risk & Vulnerability Analyzer",
      "Integração de fatores naturais e antrópicos",
      "Geração de índices de vulnerabilidade e risco",
      "Mapas técnicos para planejamento, perícia e licenciamento",
    ],
    outcome: "Você domina a metodologia completa para avaliar vulnerabilidades e riscos ambientais, gerando mapas e análises técnicas profissionais para planejamento, licenciamento e perícias.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "geoai-classificacao-uso-solo-sentinel-2",
    title: "GeoAI: Classificação de Uso e Cobertura da Terra com Sentinel-2",
    subtitle: "Classifique uso e cobertura da terra com imagens Sentinel-2 e Machine Learning, aplicando Random Forest em um pipeline automatizado e reprodutível.",
    level: "Workflow Completo",
    duration: "12h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["GeoAI", "Sentinel-2", "Classificação", "Automação"],
    image: "/courses/geoai-classificacao-uso-solo-sentinel-2.png",
    bullets: [
      "Acesso à Ferramenta Sentinel-2 GeoAI Pipeline",
      "Preparação automática das bandas espectrais",
      "Classificação supervisionada com Random Forest",
      "Mapas técnicos de uso e cobertura da terra em alta resolução",
    ],
    outcome: "Você domina a metodologia completa de GeoAI para classificação de uso e cobertura da terra com Sentinel-2, gerando mapas confiáveis e de alta resolução para análise ambiental, agrícola e territorial.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "geoai-monitoramento-historico-landsat",
    title: "GeoAI: Monitoramento Histórico de Uso e Cobertura da Terra com Landsat",
    subtitle: "Reconstrua a dinâmica do uso e cobertura da terra ao longo de décadas com imagens Landsat e Machine Learning, aplicando classificação temporal automatizada.",
    level: "Workflow Completo",
    duration: "12h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["GeoAI", "Landsat", "Série Temporal", "Automação"],
    image: "/courses/geoai-monitoramento-historico-landsat.png",
    bullets: [
      "Acesso à Ferramenta Landsat GeoAI Time Series",
      "Preparação automática da série histórica Landsat",
      "Classificação supervisionada com Random Forest",
      "Mapas e métricas temporais de mudança do uso e cobertura da terra",
    ],
    outcome: "Você domina a metodologia completa de GeoAI para monitoramento histórico de uso e cobertura da terra com Landsat, gerando séries temporais confiáveis e análises de mudança ao longo de décadas.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "geoai-alta-resolucao-cbers-4a",
    title: "GeoAI: Alta Resolução com CBERS-4A",
    subtitle: "Classifique uso do solo em alta resolução utilizando imagens CBERS-4A e Machine Learning, aplicando um pipeline automatizado e reprodutível.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["GeoAI", "CBERS-4A", "Alta Resolução", "Automação"],
    image: "/courses/geoai-alta-resolucao-cbers-4a.png",
    bullets: [
      "Acesso à Ferramenta CBERS-4A GeoAI Pipeline",
      "Preparação automática das imagens WPM",
      "Classificação supervisionada com Random Forest",
      "Mapas técnicos em alta resolução para análise detalhada",
    ],
    outcome: "Você domina a metodologia completa de GeoAI para classificação de uso e cobertura da terra com CBERS-4A, gerando mapas detalhados e de alta resolução para aplicações ambientais, urbanas e agrícolas.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "geoai-mapeamento-radar-sentinel-1",
    title: "GeoAI: Mapeamento com Radar (Sentinel-1)",
    subtitle: "Mapeie uso e cobertura da terra em qualquer condição climática utilizando imagens Radar Sentinel-1 e Machine Learning em um workflow automatizado.",
    level: "Workflow Completo",
    duration: "12h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["GeoAI", "Sentinel-1", "Radar SAR", "Automação"],
    image: "/courses/geoai-mapeamento-radar-sentinel-1.png",
    bullets: [
      "Acesso à Ferramenta Sentinel-1 GeoAI SAR Pipeline",
      "Pré-processamento automático de imagens SAR",
      "Classificação com Machine Learning em dados radar",
      "Mapas técnicos independentes de nuvens",
    ],
    outcome: "Você domina a metodologia completa de GeoAI para mapeamento de uso e cobertura da terra com Sentinel-1, gerando mapas confiáveis mesmo em áreas com alta cobertura de nuvens.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "modelagem-espacializacao-climatica",
    title: "Modelagem e Espacialização Climática",
    subtitle: "Transforme dados climáticos pontuais em superfícies contínuas e modele variáveis climáticas por meio de interpolação e rotinas automatizadas.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Clima", "Modelagem", "Espacialização", "Automação"],
    image: "/courses/modelagem-espacializacao-climatica.png",
    bullets: [
      "Acesso à Ferramenta Climate Spatial Modeler",
      "Interpolação automática de variáveis climáticas",
      "Modelagem espacial de chuva e temperatura",
      "Mapas climáticos prontos para análise ambiental",
    ],
    outcome: "Você domina a metodologia completa para modelagem e espacialização climática, gerando superfícies contínuas de variáveis climáticas com padrão técnico e reprodutível para análises ambientais e hidrológicas.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "morfometria-bacias-hidrograficas",
    title: "Morfometria de Bacias Hidrográficas",
    subtitle: "Gere automaticamente rede de drenagem, delimitação de bacias e parâmetros morfométricos essenciais para análises hidrológicas e ambientais.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Bacias", "Morfometria", "Drenagem", "Automação"],
    image: "/courses/morfometria-bacias-hidrograficas.png",
    bullets: [
      "Acesso à Ferramenta Basin Morphometry Extractor",
      "Delimitação automática de bacias e sub-bacias",
      "Extração de rede de drenagem e hierarquização",
      "Relatórios morfométricos prontos para estudos técnicos",
    ],
    outcome: "Você domina a metodologia completa para análise morfométrica de bacias hidrográficas, gerando mapas e relatórios técnicos com padrão reprodutível para estudos hidrológicos e ambientais.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "monitoramento-remoto-qualidade-agua",
    title: "Monitoramento Remoto da Qualidade da Água",
    subtitle: "Estime parâmetros de qualidade da água por sensoriamento remoto e gere mapas e séries temporais de turbidez, clorofila e material em suspensão com rotinas automatizadas.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Água", "Qualidade", "Sensoriamento", "Automação"],
    image: "/courses/monitoramento-remoto-qualidade-agua.png",
    bullets: [
      "Acesso à Ferramenta Water Quality Remote Analyzer",
      "Estimativa de turbidez e material em suspensão",
      "Modelagem de clorofila e indicadores bio-ópticos",
      "Mapas e séries temporais prontos para gestão hídrica",
    ],
    outcome: "Você domina a metodologia completa para monitoramento remoto da qualidade da água, gerando mapas e séries temporais aplicáveis à gestão e diagnóstico ambiental de recursos hídricos.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "mapeamento-aereo-drones-vant",
    title: "Mapeamento Aéreo com Drones (VANT)",
    subtitle: "Execute o fluxo completo de mapeamento aéreo com drones, do planejamento de voo à geração de ortomosaicos e modelos digitais com padrão técnico profissional.",
    level: "Workflow Completo",
    duration: "12h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Drones", "VANT", "Fotogrametria", "Automação"],
    image: "/courses/mapeamento-aereo-drones-vant.png",
    bullets: [
      "Acesso à Ferramenta Drone Mapping Workflow",
      "Planejamento de voo e coleta de imagens",
      "Processamento fotogramétrico automatizado",
      "Ortofoto, MDS e MDT prontos para análise",
    ],
    outcome: "Você domina o fluxo completo de mapeamento aéreo com drones, gerando ortomosaicos, modelos digitais de superfície e terreno com padrão técnico aplicável a projetos ambientais, agrícolas e territoriais.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "monitoramento-inteligente-irrigacao",
    title: "Monitoramento Inteligente de Irrigação",
    subtitle: "Monitore pivôs centrais e áreas irrigadas com sensoriamento remoto e índices de estresse hídrico, aplicando rotinas automatizadas para suporte à decisão agrícola.",
    level: "Workflow Completo",
    duration: "10h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Irrigação", "Agricultura", "Sensoriamento", "Automação"],
    image: "/courses/monitoramento-inteligente-irrigacao.png",
    bullets: [
      "Acesso à Ferramenta Irrigation Smart Monitor",
      "Identificação automática de áreas irrigadas",
      "Cálculo de índices de estresse hídrico",
      "Mapas e diagnósticos para manejo da irrigação",
    ],
    outcome: "Você domina a metodologia completa para monitoramento inteligente de irrigação, gerando mapas e diagnósticos de suporte à tomada de decisão no agronegócio com base em sensoriamento remoto.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "estatistica-geoestatistica-agricola",
    title: "Estatística e Geoestatística Agrícola",
    subtitle: "Aplique estatística descritiva e geoestatística para analisar dados agrícolas e gerar mapas confiáveis de fertilidade, produtividade e variabilidade espacial.",
    level: "Workflow Completo",
    duration: "12h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Estatística", "Geoestatística", "Agricultura", "Automação"],
    image: "/courses/estatistica-geoestatistica-agricola.png",
    bullets: [
      "Acesso à Ferramenta Geoestatística Agrícola",
      "Estatística aplicada a dados agrícolas",
      "Variogramas e modelos de dependência espacial",
      "Mapas por krigagem prontos para decisão",
    ],
    outcome: "Você domina a metodologia completa de estatística e geoestatística agrícola, gerando mapas confiáveis de fertilidade, produtividade e variabilidade espacial para suporte à tomada de decisão no agronegócio.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "geotecnologias-como-metodo-cientifico",
    title: "Geotecnologias como Suporte Científico",
    subtitle: "Aplicação correta de geotecnologias em TCCs, dissertações e teses, com rigor científico.",
    level: "Graduação ao Doutorado",
    duration: "5h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Pesquisa", "Academia", "Geotecnologias", "Suporte Científico"],
    image: "/courses/geotecnologias-como-metodo-cientifico.png",
    bullets: [
      "Uso científico correto das geotecnologias",
      "Integração metodológica em pesquisas acadêmicas",
      "Evitar mapas ilustrativos sem rigor científico",
      "Base conceitual para estudos avançados",
    ],
    outcome: "Você domina o uso metodologicamente fundamentado das geotecnologias em pesquisas acadêmicas, aplicando corretamente em TCCs, dissertações e teses com rigor científico.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "erros-cartograficos-comprometem-mapa",
    title: "Erros Cartográficos que Comprometem Seu Mapa",
    subtitle: "Evite erros de projeção, escala e simbologia que invalidam mapas técnicos e científicos.",
    level: "Workflow Completo",
    duration: "4h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Cartografia", "Mapas", "Qualidade Técnica", "Pesquisa"],
    image: "/courses/erros-cartograficos-comprometem-mapa.png",
    bullets: [
      "Erros de projeção e coordenadas",
      "Problemas de escala e resolução",
      "Falhas de simbologia e legenda",
      "Avaliação crítica de mapas",
    ],
    outcome: "Você domina a identificação e prevenção de erros cartográficos que comprometem a leitura, interpretação e validade científica de mapas técnicos e acadêmicos.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "analise-ambiental-integrada-geossistemas",
    title: "Análise Ambiental Integrada por Geossistemas",
    subtitle: "Pensamento sistêmico aplicado à análise ambiental com base geográfica.",
    level: "Workflow Completo",
    duration: "5h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Geossistema", "Análise Ambiental", "Integração", "Território"],
    image: "/courses/analise-ambiental-integrada-geossistemas.png",
    bullets: [
      "Pensamento sistêmico aplicado",
      "Integração relevo, solo e uso da terra",
      "Análises ambientais consistentes",
      "Base conceitual para estudos avançados",
    ],
    outcome: "Você domina a análise ambiental integrada a partir do conceito de geossistema, aplicando pensamento sistêmico para análises ambientais consistentes e integradas.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "introducao-cartografia-digital",
    title: "Introdução à Cartografia Digital",
    subtitle: "Fundamentos cartográficos para representação correta do espaço em estudos acadêmicos e técnicos.",
    level: "Workflow Completo",
    duration: "4h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Cartografia", "Mapas", "Representação Espacial", "Academia"],
    image: "/courses/introducao-cartografia-digital.png",
    bullets: [
      "Fundamentos da cartografia moderna",
      "Escala, projeção e sistema de coordenadas",
      "Representação espacial adequada",
      "Base cartográfica para estudos científicos",
    ],
    outcome: "Você domina os fundamentos da cartografia digital e produz mapas tecnicamente corretos, coerentes com escala, projeção e objetivo do estudo.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "sensoriamento-remoto-fundamentos-analise-cientifica",
    title: "Sensoriamento Remoto: Fundamentos para Análise Científica",
    subtitle: "Fundamentos físicos e conceituais do sensoriamento remoto aplicados à análise ambiental e territorial.",
    level: "Workflow Completo",
    duration: "5h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Sensoriamento Remoto", "Imagens de Satélite", "Academia", "Análise Ambiental"],
    image: "/courses/sensoriamento-remoto-fundamentos-analise-cientifica.png",
    bullets: [
      "Fundamentos físicos do sensoriamento remoto",
      "Resolução espacial, espectral e temporal",
      "Limites e potencial das imagens de satélite",
      "Base conceitual para análises ambientais",
    ],
    outcome: "Você domina os fundamentos do sensoriamento remoto e interpreta imagens de satélite com rigor científico, evitando erros conceituais comuns em estudos acadêmicos.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
  {
    slug: "geotecnologias-estudo-mudancas-climaticas",
    title: "Geotecnologias no Estudo das Mudanças Climáticas",
    subtitle: "Uso científico de dados espaciais e climáticos na análise de mudanças climáticas em escala territorial.",
    level: "Workflow Completo",
    duration: "5h",
    priceText: "Lançamento em breve",
    hotmartCheckoutUrl: "https://pay.hotmart.com/SEU_CHECKOUT_AQUI",
    tags: ["Mudanças Climáticas", "Geotecnologias", "Clima", "Análise Ambiental"],
    image: "/courses/geotecnologias-estudo-mudancas-climaticas.png",
    bullets: [
      "Uso científico de dados climáticos",
      "Integração clima, uso da terra e relevo",
      "Limites e incertezas em mapas climáticos",
      "Leitura crítica de indicadores climáticos",
    ],
    outcome: "Você domina o uso científico de geotecnologias em estudos de mudanças climáticas, avaliando dados, mapas e indicadores com rigor científico e senso crítico.",
    instructor: "Wellmo Alves",
    isPromo: false,
  },
];

export function getCourseBySlug(slug: string) {
  return COURSES.find((c) => c.slug === slug);
}
